# Permalinks
permalink:           pretty

# Setup
title:               Computational and Evolutionary Biology Tips
tagline:             A resource to share problem solutions in computational biology and evolutionary biology
url:                 https://fortune9.github.io/
baseurl:             /comp_evol
analytics_id:
exclude: []
port: 8080

# Owner/author information
owner:
  name:           Zhenguo Zhang
  avatar:         avatar.png
  bio:            "Computational Biologist"
  email:          zhangz.sci@gmail.com
  twitter:        fortunezhang
  github:         fortune9
  location:       "Rochester, NY"


# Custom vars
version:             2.0.0
github:
  repo:              

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate
